#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARG BASE_IMAGE=apache/spark:4.1.0-preview1-scala2.13-java17-ubuntu
FROM $BASE_IMAGE

COPY .local/spark-defaults.conf /opt/spark/conf/
COPY target/okdp-spark-auth-filter-*-SNAPSHOT-jakarta.jar /opt/spark/jars/

