name: release-please

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # Only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    # Skip the release process in the fork
    # The pull request should come from the same repo (github_token from the fork does not have write permissions)
    if: github.repository_owner == 'OKDP' && github.event.pull_request.merged == true && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please

  publish-maven-central:
    runs-on: ubuntu-latest
    needs: [release-please]
    if: github.repository_owner == 'OKDP' && needs.release-please.outputs.release_created == 'true'
    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up GitHub Actions git bot 📦
        uses: ./.github/actions/setup-git-bot

      - name: Set up JDK 11 📦
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'
          check-latest: true
          server-id: 'central'
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Publish the tag '${{ needs.release-please.outputs.tag_name }}' to maven central 📤
        run: |
          git checkout tags/${{ needs.release-please.outputs.tag_name }}
          mvn clean deploy -Prelease -DskipTests
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}





